const data = {
  products: [
    {
      name: 'Titan Black',
      slug: 'titan-black-analog',
      category: 'Unisex',
      image: '/images/Titan.jpg',
      price: 120,
      countInStock: 10,
      brand: 'Titan',
      rating: 4.5,
      numReviews: 10,
      description: 'titan black (shiny) unisex',
    },
    {
      name: 'Losian Luxury',
      slug: 'losian-luxury-black',
      category: 'Unisex',
      image: '/images/Losianluxury.jpg',
      price: 89,
      countInStock: 15,
      brand: 'Losian',
      rating: 4.3,
      numReviews: 9,
      description: 'losian luxury black',
    },
    {
      name: 'Michael Kors Bradshaw',
      slug: 'michael-kors-bradshaw',
      category: 'Mens',
      image: '/images/Michael_Kors-Bradshaw.jpg',
      price: 100,
      countInStock: 5,
      brand: 'Michael Kors',
      rating: 3,
      numReviews: 15,
      description: 'michael kors bradshaw black',
    },
    {
      name: 'Quartz Economicxi',
      slug: 'economicxi-quartz-black',
      category: 'Mens',
      image: '/images/Economicxi.jpg',
      price: 190,
      countInStock: 8,
      brand: 'Economicxi',
      rating: 4,
      numReviews: 12,
      description: 'economicxi quartz black',
    },
  ],
};
export default data;
